import { Inter } from "next/font/google";
import "./globals.css";
import CustomLayout from "./components/CustomLayout.js";
import { LoadingAnimationContextProvider } from "./context/loadingAnimationContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <LoadingAnimationContextProvider>
          <CustomLayout>{children}</CustomLayout>
        </LoadingAnimationContextProvider>
      </body>
    </html>
  );
}
